exclude: '.qmlproject$'

repos:
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: ad270fb9db427f956ce8eb50c74617ed117b9bfc
      hooks:
        - id: clang-format
          types_or: [c++, c, cuda]

    - repo: https://github.com/cheshirekow/cmake-format-precommit
      rev: e2c2116d86a80e72e7146a06e68b7c228afc6319
      hooks:
        - id: cmake-format

    - repo: https://github.com/machinekoder/pre-commit-hooks
      rev: 9e441cae733432906f2e815803b3b52513356a0f
      hooks:
        - id: qmlfmt
          entry: qmlformat -n -i

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 0d20f18212d68260c0c3600d0d94587d9ead20e5
      hooks:
        - id: check-case-conflict
        - id: check-yaml
        - id: check-json
        - id: check-xml
        - id: pretty-format-json
          args: [
            '--autofix'
          ]
        - id: end-of-file-fixer
        - id: mixed-line-ending
