find_path(RXQT_INCLUDE_DIRS "rxqt.hpp")

if(NOT DEFINED RXQT_INCLUDE_DIRS OR ${RXQT_INCLUDE_DIRS} STREQUAL "RXQT_INCLUDE_DIRS-NOTFOUND")
	set(RXQT_FOUND False)
else()
	add_library(RXQT INTERFACE)

	target_include_directories(RXQT INTERFACE ${RXQT_INCLUDE_DIRS})

	set(RXQT_FOUND True)
endif()